### ISSUE TITLE
Feature: Dropdown component

### ISSUE THREAD

**Issue by k11q** [khairulhaaziq/noir-ui#1]
# Dropdown Component

## Completed

- [x]  Keyboard: When focus on trigger: Press Space key to open the Menu.
- [x]  Keyboard: When focus on trigger: Press Up and Down arrow keys to open the Menu.
- [x]  Keyboard: When opened: Press Space or Enter keys to select the highlighted option.
- [x]  Keyboard: When opened: Press Esc to close the Menu.
- [x]  Keyboard: When opened: Press Up and Down arrow keys to navigate across options.
- [x]  Positioning: Default position at selected.
- [x]  Focus trap
- [x]  Block clicks outside

## Todos

- [ ]  Screen reader.
- [ ] Typeahead
- [ ]  Collision aware.
- [ ]  Scroll indicators.
- [ ]  Scroll based height
- [ ]  Native fallback.
- [ ]  Autofill
- [ ]  Scroll lock

### Root

- open - default: false
- defaultOpen - default: false
- dir - default: 'ltr'

### Trigger

- className - default: ''

### Portal

- className - default: ''

### Group

- label - default: ''

### Arrow

- width - default: 8
- height - default: 8

### Item

- 

## Reference:

Thank you Pedro Duarte and the Radix/Modulz team for the great [resources](https://modulz.app/blog/under-the-spotlight-select)
