### ISSUE TITLE
Feature: Accordion

### ISSUE THREAD

**Issue by k11q** [khairulhaaziq/noir-ui#2]
# Accordion

## Features:

- Full keyboard navigation.
- Can expand one or multiple items.
- Can be controlled or uncontrolled.

## Completed
- [x] Keyboard: Tab native behaviour.

## Todo

- [ ] Keyboard: Arrow up/down to move focus/select accordion.
- [ ] Keyboard: Space/Enter to expand/close accordion.
